version: '3.8'

services:
  web:
    env_file: docker.env
    build:
      context: .
      args:
      - ${TARGET:-debug}
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - db_network
    volumes:
      - ./coverage:/usr/src/app/coverage

  db:
    env_file: docker.env
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    networks:
      - db_network

volumes:
  postgres_data:
  coverage:

networks:
  db_network:
