"""Add product

Revision ID: bc59021473f5
Revises:
Create Date: 2022-12-22 23:51:32.794546

"""
import sqlalchemy as sa
import sqlmodel  # NEW

from alembic import op

# revision identifiers, used by Alembic.
revision = "bc59021473f5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("receipt", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "image", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("calories", sa.Float(), nullable=True),
        sa.Column("proteins", sa.Float(), nullable=True),
        sa.Column("fats", sa.Float(), nullable=True),
        sa.Column("carbohydrates", sa.Float(), nullable=True),
        sa.Column("is_dish", sa.Boolean(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.Column("weight", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_product_id"), "product", ["id"], unique=False)
    op.create_table(
        "dish_components_link",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("dish_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("component_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["dish_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id", "dish_id", "component_id"),
    )
    op.create_index(
        op.f("ix_dish_components_link_id"), "dish_components_link", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dish_components_link_id"), table_name="dish_components_link")
    op.drop_table("dish_components_link")
    op.drop_index(op.f("ix_product_id"), table_name="product")
    op.drop_table("product")
    # ### end Alembic commands ###
