"""Change collation

Revision ID: 82a96e91e84f
Revises: 24db88e78218
Create Date: 2022-12-23 12:16:34.397219

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "82a96e91e84f"
down_revision = "24db88e78218"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        'ALTER TABLE product ALTER COLUMN name SET DATA TYPE varchar COLLATE "uk_UA"'
    )


def downgrade() -> None:
    op.execute(
        'ALTER TABLE product ALTER COLUMN name SET DATA TYPE varchar COLLATE "en_US"'
    )
